config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :events

  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
  end

  def create
    @event = Event.new(event_params)

    @event.save
    redirect_to @event
  end

  def show
      @event = Event.find(params[:id])
  end

  private
    def event_params
      params.require(:event).permit(:home, :away, :eventdate, :status)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/index.html.erb
<h1>Listing Events</h1>
<%= link_to 'New Event', new_event_path %>
<table>
  <tr>
    <th>Event Date</th>
    <th>Home</th>
    <th>Away</th>
    <th>Status</th>
  </tr>

  <% @events.each do |event| %>
    <tr>
      <td><%= event.eventdate %></td>
      <td><%= event.home %></td>
      <td><%= event.away %></td>
      <td><%= event.status %></td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<%= form_for :event, url: events_path do |f| %>
  <p>
    <%= f.label :home %><br>
    <%= f.select :home, [['Chelsea','Chelsea'],['Manchester United','ManchesterUnited'],['Liverpool','Liverpool']] %>
  </p>

  <p>
    <%= f.label :away %><br>
    <%= f.select :away, [['Chelsea','Chelsea'],['Manchester United','ManchesterUnited'],['Liverpool','Liverpool']] %>
  </p>

  <p>
    <%= f.datetime_select :eventdate%>
  </p>

  <p>
    <%= f.label :status %><br>
    <%= f.select :status, [['Running','Running'],['Closed','Closed']] %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <strong>Home:</strong>
  <%= @event.home %>
</p>

<p>
  <strong>Away:</strong>
  <%= @event.away %>
</p>

<p>
  <strong>Event Date:</strong>
  <%= @event.eventdate %>
</p>

<p>
  <strong>Status:</strong>
  <%= @event.status %>
</p>

<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simplebet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails</h1>
<%= link_to 'Events', controller: 'events' %>